FROM mcr.microsoft.com/dotnet/aspnet:8.0.7-noble-chiseled-extra-amd64 as debug
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS service
FROM mcr.microsoft.com/dotnet/aspnet:8.0.7-noble-chiseled-extra-amd64 as publish
